### YamlMime:ManagedReference
items:
- uid: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail
  commentId: T:Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail
  id: OrderEmailTemplateSettingDetail
  parent: Uvendia.Domain.Settings
  children:
  - Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailAssemblyTypeName
  - Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailTemplatePath
  - Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.IsEmpty
  - Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.LanguageCultureName
  langs:
  - csharp
  - vb
  name: OrderEmailTemplateSettingDetail
  nameWithType: OrderEmailTemplateSettingDetail
  fullName: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail
  type: Class
  source:
    remote:
      path: Uvendia.Domain/Settings/OrderEmailTemplateSetting.cs
      branch: umbraco8
      repo: https://sherlonus@bitbucket.org/sherlonus/dazzling.studio.git
    id: OrderEmailTemplateSettingDetail
    path: ../../dazzling.studio/Uvendia.Domain/Settings/OrderEmailTemplateSetting.cs
    startLine: 29
  assemblies:
  - Uvendia.Domain
  namespace: Uvendia.Domain.Settings
  syntax:
    content: public class OrderEmailTemplateSettingDetail
    content.vb: Public Class OrderEmailTemplateSettingDetail
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.LanguageCultureName
  commentId: P:Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.LanguageCultureName
  id: LanguageCultureName
  parent: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail
  langs:
  - csharp
  - vb
  name: LanguageCultureName
  nameWithType: OrderEmailTemplateSettingDetail.LanguageCultureName
  fullName: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.LanguageCultureName
  type: Property
  source:
    remote:
      path: Uvendia.Domain/Settings/OrderEmailTemplateSetting.cs
      branch: umbraco8
      repo: https://sherlonus@bitbucket.org/sherlonus/dazzling.studio.git
    id: LanguageCultureName
    path: ../../dazzling.studio/Uvendia.Domain/Settings/OrderEmailTemplateSetting.cs
    startLine: 31
  assemblies:
  - Uvendia.Domain
  namespace: Uvendia.Domain.Settings
  syntax:
    content: >-
      [Required]

      public string LanguageCultureName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required>

      Public Property LanguageCultureName As String
  overload: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.LanguageCultureName*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailTemplatePath
  commentId: P:Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailTemplatePath
  id: EmailTemplatePath
  parent: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail
  langs:
  - csharp
  - vb
  name: EmailTemplatePath
  nameWithType: OrderEmailTemplateSettingDetail.EmailTemplatePath
  fullName: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailTemplatePath
  type: Property
  source:
    remote:
      path: Uvendia.Domain/Settings/OrderEmailTemplateSetting.cs
      branch: umbraco8
      repo: https://sherlonus@bitbucket.org/sherlonus/dazzling.studio.git
    id: EmailTemplatePath
    path: ../../dazzling.studio/Uvendia.Domain/Settings/OrderEmailTemplateSetting.cs
    startLine: 35
  assemblies:
  - Uvendia.Domain
  namespace: Uvendia.Domain.Settings
  syntax:
    content: public string EmailTemplatePath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property EmailTemplatePath As String
  overload: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailTemplatePath*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailAssemblyTypeName
  commentId: P:Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailAssemblyTypeName
  id: EmailAssemblyTypeName
  parent: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail
  langs:
  - csharp
  - vb
  name: EmailAssemblyTypeName
  nameWithType: OrderEmailTemplateSettingDetail.EmailAssemblyTypeName
  fullName: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailAssemblyTypeName
  type: Property
  source:
    remote:
      path: Uvendia.Domain/Settings/OrderEmailTemplateSetting.cs
      branch: umbraco8
      repo: https://sherlonus@bitbucket.org/sherlonus/dazzling.studio.git
    id: EmailAssemblyTypeName
    path: ../../dazzling.studio/Uvendia.Domain/Settings/OrderEmailTemplateSetting.cs
    startLine: 38
  assemblies:
  - Uvendia.Domain
  namespace: Uvendia.Domain.Settings
  syntax:
    content: >-
      [StringLength(500)]

      public string EmailAssemblyTypeName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <StringLength(500)>

      Public Property EmailAssemblyTypeName As String
  overload: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailAssemblyTypeName*
  attributes:
  - type: System.ComponentModel.DataAnnotations.StringLengthAttribute
    ctor: System.ComponentModel.DataAnnotations.StringLengthAttribute.#ctor(System.Int32)
    arguments:
    - type: System.Int32
      value: 500
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.IsEmpty
  commentId: M:Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.IsEmpty
  id: IsEmpty
  parent: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail
  langs:
  - csharp
  - vb
  name: IsEmpty()
  nameWithType: OrderEmailTemplateSettingDetail.IsEmpty()
  fullName: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.IsEmpty()
  type: Method
  source:
    remote:
      path: Uvendia.Domain/Settings/OrderEmailTemplateSetting.cs
      branch: umbraco8
      repo: https://sherlonus@bitbucket.org/sherlonus/dazzling.studio.git
    id: IsEmpty
    path: ../../dazzling.studio/Uvendia.Domain/Settings/OrderEmailTemplateSetting.cs
    startLine: 42
  assemblies:
  - Uvendia.Domain
  namespace: Uvendia.Domain.Settings
  syntax:
    content: public bool IsEmpty()
    return:
      type: System.Boolean
    content.vb: Public Function IsEmpty As Boolean
  overload: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.IsEmpty*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Uvendia.Domain.Settings
  commentId: N:Uvendia.Domain.Settings
  name: Uvendia.Domain.Settings
  nameWithType: Uvendia.Domain.Settings
  fullName: Uvendia.Domain.Settings
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.LanguageCultureName*
  commentId: Overload:Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.LanguageCultureName
  name: LanguageCultureName
  nameWithType: OrderEmailTemplateSettingDetail.LanguageCultureName
  fullName: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.LanguageCultureName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailTemplatePath*
  commentId: Overload:Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailTemplatePath
  name: EmailTemplatePath
  nameWithType: OrderEmailTemplateSettingDetail.EmailTemplatePath
  fullName: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailTemplatePath
- uid: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailAssemblyTypeName*
  commentId: Overload:Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailAssemblyTypeName
  name: EmailAssemblyTypeName
  nameWithType: OrderEmailTemplateSettingDetail.EmailAssemblyTypeName
  fullName: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.EmailAssemblyTypeName
- uid: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.IsEmpty*
  commentId: Overload:Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.IsEmpty
  name: IsEmpty
  nameWithType: OrderEmailTemplateSettingDetail.IsEmpty
  fullName: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail.IsEmpty
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
