### YamlMime:ManagedReference
items:
- uid: Uvendia.Domain.Settings
  commentId: N:Uvendia.Domain.Settings
  id: Uvendia.Domain.Settings
  children:
  - Uvendia.Domain.Settings.AvailableInCountry
  - Uvendia.Domain.Settings.eTicketSetting
  - Uvendia.Domain.Settings.eTicketSettingDetail
  - Uvendia.Domain.Settings.InvoiceSetting
  - Uvendia.Domain.Settings.InvoiceSettingDetail
  - Uvendia.Domain.Settings.OrderEmailTemplateSetting
  - Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail
  - Uvendia.Domain.Settings.OrderNumber
  - Uvendia.Domain.Settings.SerializedSettings
  - Uvendia.Domain.Settings.TicketType
  langs:
  - csharp
  - vb
  name: Uvendia.Domain.Settings
  nameWithType: Uvendia.Domain.Settings
  fullName: Uvendia.Domain.Settings
  type: Namespace
  assemblies:
  - Uvendia.Domain
references:
- uid: Uvendia.Domain.Settings.AvailableInCountry
  commentId: T:Uvendia.Domain.Settings.AvailableInCountry
  parent: Uvendia.Domain.Settings
  name: AvailableInCountry
  nameWithType: AvailableInCountry
  fullName: Uvendia.Domain.Settings.AvailableInCountry
- uid: Uvendia.Domain.Settings.OrderEmailTemplateSetting
  commentId: T:Uvendia.Domain.Settings.OrderEmailTemplateSetting
  parent: Uvendia.Domain.Settings
  name: OrderEmailTemplateSetting
  nameWithType: OrderEmailTemplateSetting
  fullName: Uvendia.Domain.Settings.OrderEmailTemplateSetting
- uid: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail
  commentId: T:Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail
  name: OrderEmailTemplateSettingDetail
  nameWithType: OrderEmailTemplateSettingDetail
  fullName: Uvendia.Domain.Settings.OrderEmailTemplateSettingDetail
- uid: Uvendia.Domain.Settings.eTicketSetting
  commentId: T:Uvendia.Domain.Settings.eTicketSetting
  parent: Uvendia.Domain.Settings
  name: eTicketSetting
  nameWithType: eTicketSetting
  fullName: Uvendia.Domain.Settings.eTicketSetting
- uid: Uvendia.Domain.Settings.eTicketSettingDetail
  commentId: T:Uvendia.Domain.Settings.eTicketSettingDetail
  name: eTicketSettingDetail
  nameWithType: eTicketSettingDetail
  fullName: Uvendia.Domain.Settings.eTicketSettingDetail
- uid: Uvendia.Domain.Settings.OrderNumber
  commentId: T:Uvendia.Domain.Settings.OrderNumber
  parent: Uvendia.Domain.Settings
  name: OrderNumber
  nameWithType: OrderNumber
  fullName: Uvendia.Domain.Settings.OrderNumber
- uid: Uvendia.Domain.Settings.SerializedSettings
  commentId: T:Uvendia.Domain.Settings.SerializedSettings
  parent: Uvendia.Domain.Settings
  name: SerializedSettings
  nameWithType: SerializedSettings
  fullName: Uvendia.Domain.Settings.SerializedSettings
- uid: Uvendia.Domain.Settings.InvoiceSetting
  commentId: T:Uvendia.Domain.Settings.InvoiceSetting
  parent: Uvendia.Domain.Settings
  name: InvoiceSetting
  nameWithType: InvoiceSetting
  fullName: Uvendia.Domain.Settings.InvoiceSetting
- uid: Uvendia.Domain.Settings.InvoiceSettingDetail
  commentId: T:Uvendia.Domain.Settings.InvoiceSettingDetail
  name: InvoiceSettingDetail
  nameWithType: InvoiceSettingDetail
  fullName: Uvendia.Domain.Settings.InvoiceSettingDetail
- uid: Uvendia.Domain.Settings.TicketType
  commentId: T:Uvendia.Domain.Settings.TicketType
  parent: Uvendia.Domain.Settings
  name: TicketType
  nameWithType: TicketType
  fullName: Uvendia.Domain.Settings.TicketType
- uid: Uvendia.Domain.Settings
  commentId: N:Uvendia.Domain.Settings
  name: Uvendia.Domain.Settings
  nameWithType: Uvendia.Domain.Settings
  fullName: Uvendia.Domain.Settings
